---
- hosts: all
  gather_facts: no

- import_playbook: playbooks/terminal.yaml
- import_playbook: playbooks/oh-my-zsh.yaml
- import_playbook: playbooks/desktop.yaml
- import_playbook: playbooks/boring-desktop.yaml
- import_playbook: playbooks/aliases.yaml
- import_playbook: playbooks/databases.yaml
- import_playbook: playbooks/taps.yaml
