---
- name: Install problematic desktop environment
  hosts: all
  gather_facts: no

  vars:
    cask_packages:
      - anydesk
      - deezer
      - discord
      - postman
      - microsoft-teams

  tasks:
    - name: Install Homebrew Cask packages
      homebrew_cask: name={{ item }} state=present
      with_items: "{{ cask_packages }}"

