---
- name: Install databases
  hosts: all
  gather_facts: no

  vars:
    packages:
      # - elasticsearch
      - mysql
      - postgres
      - redis

  tasks:
    - name: Install Homebrew packages
      homebrew: name={{ packages }} state=latest
