---
- name: Install oh-my-zsh and configure ssh
  hosts: all
  gather_facts: yes

# Inspired by https://github.com/RaymiiOrg/ansible/blob/master/oh-my-zsh/ohmyzsh.yml

  vars:
    oh_my_zsh_repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    oh_my_zsh_dir: "~/.oh-my-zsh"
    zsh_syntax_highlighting_repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    zsh_syntax_highlighting_dir: "~/zsh-syntax-highlighting"
    zshrc: "templates/shell/.zshrc"
    src_gitconfig: "templates/shell/gitconfig"
    dst_gitconfig: "~/.gitconfig"


  tasks:
    - name: Clone oh-my-zsh repository
      git: repo="{{ oh_my_zsh_repo }}" dest="{{ oh_my_zsh_dir }}" version=master

    - name: Install zshrc
      copy: src="{{ zshrc }}" dest="{{ ansible_user_dir }}" mode=0640

    - name: Install gitconfig
      copy: src="{{ src_gitconfig }}" dest="{{ dst_gitconfig }}" mode=0644

    - name: Set zsh as default shell
      user: name={{ ansible_user_id }} shell=/bin/zsh

    - name: Clone zsh-syntax-highlighting repository
      git: repo="{{ zsh_syntax_highlighting_repo }}" dest="{{ zsh_syntax_highlighting_dir }}" version=master
      